# Generated by Django 3.1.14 on 2022-04-08 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='Todo',
        ),
    ]
