# Generated by Django 3.1.14 on 2022-04-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220408_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='complite',
            field=models.DateField(blank=True, null=True, verbose_name='完了日'),
        ),
    ]
